// Date: 1/12/2015 8:02:51 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package me.hii488.moRandomStuff.Models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelMonoclePig extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer M1;
    ModelRenderer M2;
    ModelRenderer M3;
    ModelRenderer M4;
    ModelRenderer M5;
    ModelRenderer M6;
    ModelRenderer M7;
    ModelRenderer M8;
    ModelRenderer M9;
    ModelRenderer M10;
    ModelRenderer M11;
    ModelRenderer M12;
    ModelRenderer Shape1;
  
  public ModelMonoclePig()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -4F, -8F, 8, 8, 8);
      head.setRotationPoint(0F, 12F, -6F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 28, 8);
      body.addBox(-5F, -10F, -7F, 10, 16, 8);
      body.setRotationPoint(0F, 11F, 3F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 1.570796F, 0F, 0F);
      leg1 = new ModelRenderer(this, 0, 16);
      leg1.addBox(-2F, 0F, -2F, 4, 6, 4);
      leg1.setRotationPoint(-3F, 18F, 7F);
      leg1.setTextureSize(64, 32);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 0, 16);
      leg2.addBox(-2F, 0F, -2F, 4, 6, 4);
      leg2.setRotationPoint(3F, 18F, 7F);
      leg2.setTextureSize(64, 32);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 0, 16);
      leg3.addBox(-2F, 18F, -2F, 4, 6, 4);
      leg3.setRotationPoint(-3F, 0F, -5F);
      leg3.setTextureSize(64, 32);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 0, 16);
      leg4.addBox(-2F, 0F, -2F, 4, 6, 4);
      leg4.setRotationPoint(3F, 18F, -5F);
      leg4.setTextureSize(64, 32);
      leg4.mirror = true;
      setRotation(leg4, 0F, 0F, 0F);
      M1 = new ModelRenderer(this, 11, 30);
      M1.addBox(0F, 0F, 0F, 1, 1, 0);
      M1.setRotationPoint(3.5F, 9.5F, -5.5F);
      M1.setTextureSize(64, 32);
      M1.mirror = true;
      setRotation(M1, 0F, 0F, 0F);
      M2 = new ModelRenderer(this, 0, 26);
      M2.addBox(0F, 0F, 0F, 4, 3, 0);
      M2.setRotationPoint(0.5F, 9.5F, -14.5F);
      M2.setTextureSize(64, 32);
      M2.mirror = true;
      setRotation(M2, 0F, 0F, 0F);
      M3 = new ModelRenderer(this, 9, 30);
      M3.addBox(0F, 0F, 0F, 1, 0, 1);
      M3.setRotationPoint(-0.5F, 7.5F, -14.5F);
      M3.setTextureSize(64, 32);
      M3.mirror = true;
      setRotation(M3, 0F, 0F, 0F);
      M4 = new ModelRenderer(this, 8, 26);
      M4.addBox(0F, 0F, 0F, 3, 1, 0);
      M4.setRotationPoint(1.5F, 12.5F, -14.5F);
      M4.setTextureSize(64, 32);
      M4.mirror = true;
      setRotation(M4, 0F, 0F, 0F);
      M5 = new ModelRenderer(this, 11, 30);
      M5.addBox(0F, 0F, 0F, 1, 1, 0);
      M5.setRotationPoint(-2.5F, 7.5F, -5.5F);
      M5.setTextureSize(64, 32);
      M5.mirror = true;
      setRotation(M5, 0F, 0F, 0F);
      M6 = new ModelRenderer(this, 15, 25);
      M6.addBox(0F, 0F, 0F, 0, 2, 1);
      M6.setRotationPoint(4.5F, 10.5F, -14.5F);
      M6.setTextureSize(64, 32);
      M6.mirror = true;
      setRotation(M6, 0F, 0F, 0F);
      M7 = new ModelRenderer(this, 16, 26);
      M7.addBox(0F, 0F, 0F, 1, 2, 0);
      M7.setRotationPoint(-0.5F, 7.5F, -14.5F);
      M7.setTextureSize(64, 32);
      M7.mirror = true;
      setRotation(M7, 0F, 0F, 0F);
      M8 = new ModelRenderer(this, 3, 26);
      M8.addBox(0F, 0F, 0F, 0, 1, 3);
      M8.setRotationPoint(4.5F, 10.5F, -13.5F);
      M8.setTextureSize(64, 32);
      M8.mirror = true;
      setRotation(M8, 0F, 0F, 0F);
      M9 = new ModelRenderer(this, 15, 26);
      M9.addBox(0F, 0F, 0F, 1, 0, 3);
      M9.setRotationPoint(-1.5F, 7.5F, -13.5F);
      M9.setTextureSize(64, 32);
      M9.mirror = true;
      setRotation(M9, 0F, 0F, 0F);
      M10 = new ModelRenderer(this, 5, 25);
      M10.addBox(0F, 0F, 0F, 0, 1, 5);
      M10.setRotationPoint(4.5F, 9.5F, -10.5F);
      M10.setTextureSize(64, 32);
      M10.mirror = true;
      setRotation(M10, 0F, 0F, 0F);
      M11 = new ModelRenderer(this, 15, 26);
      M11.addBox(0F, 0F, 0F, 1, 0, 5);
      M11.setRotationPoint(-2.5F, 7.5F, -10.5F);
      M11.setTextureSize(64, 32);
      M11.mirror = true;
      setRotation(M11, 0F, 0F, 0F);
      M12 = new ModelRenderer(this, 11, 29);
      M12.addBox(0F, 0F, 0F, 5, 1, 0);
      M12.setRotationPoint(-1.5F, 8.5F, -5.5F);
      M12.setTextureSize(64, 32);
      M12.mirror = true;
      setRotation(M12, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 16, 16);
      Shape1.addBox(0F, 0F, 0F, 4, 3, 1);
      Shape1.setRotationPoint(-2F, 12F, -15F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    head.render(f5);
    body.render(f5);
    leg1.render(f5);
    leg2.render(f5);
    leg3.render(f5);
    leg4.render(f5);
    M1.render(f5);
    M2.render(f5);
    M3.render(f5);
    M4.render(f5);
    M5.render(f5);
    M6.render(f5);
    M7.render(f5);
    M8.render(f5);
    M9.render(f5);
    M10.render(f5);
    M11.render(f5);
    M12.render(f5);
    Shape1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
